name: "hail"
description: Hail is Python-based data analysis tool for working with genomic data, it is fast to filter samples and varaints based on QC threasholds.
keywords:
  - variant filtering
  - GWAS
  - Quality control
  - Frequency calculation
tools:
  - "hail":
      description: "Hail is Python-based data analysis tool for working with genomic data."
      homepage: "https://hail.is/"
      documentation: "https://hail.is/docs/0.2/index.html"
      tool_dev_url: "https://github.com/hail-is/hail"
      doi: "Hail Team. Hail 0.2.13-81ab564db2b4. https://github.com/hail-is/hail/releases/tag/0.2.13."
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: vcf/vcf.bgz file
      pattern: "*.{vcf,vcf.bgz}"
      
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - with_geno_vcf:
      type: file
      description: vcf/vcf.bgz file
      pattern: "*.{vcf,vcf.bgz}"
  - with_geno_index :
      type: file
      description: index file
      pattern: "*.{vcf.bgz.tbi}"
  - frequ_only_vcf:
      type: file
      description: csv/tsv file (optional)
      pattern: "*.{bam,cram,sam}"
  - frequ_only_index:
      type: file
      description: csv/tsv file (optional)
      pattern: "*.{bam,cram,sam}"
  - tsv:
      type: file
      description: csv/tsv file (optional)
      pattern: "*.{bam,cram,sam}"
  - html:
      type: file
      description: html file
      pattern: "*.{html}"
  - txt:
      type: file
      description: txt file
      pattern: "*.{txt}"

authors:
  - "@scorreard"
