name: "hail"
description: Hail is Python-based data analysis tool for working with genomic data, it is fast to filter samples and varaints based on QC threasholds.
keywords:
  - variant filtering
  - GWAS
  - Quality control
  - Frequency calculation
tools:
  - "hail":
      description: "Hail is Python-based data analysis tool for working with genomic data."
      homepage: "https://hail.is/"
      documentation: "https://hail.is/docs/0.2/index.html"
      tool_dev_url: "https://github.com/hail-is/hail"
      doi: "Hail Team. Hail 0.2.13-81ab564db2b4. https://github.com/hail-is/hail/releases/tag/0.2.13."
      licence: "['MIT']"

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@scorreard"
